call testjs app ud.js
call testjs app ude.js
call testjs app/calculator udecalc.js
call testjs app/config udeconstants.js
call testjs app/config udconstants.js
call testjs app/helpers dom.js
call testjs app/helpers domvalue.js
call testjs app/helpers domcursor.js
call testjs app/helpers udajax.js
call testjs app/helpers udeclickhandler.js
call testjs app/helpers udemenu.js
call testjs app/helpers udeideas.js
call testjs app/helpers udelayout.js
call testjs app/helpers udestyles.js
call testjs app/$$$ udapi.js
call testjs app/$$$ apiset1.js
call testjs app/$$$ apiset2.js
call testjs app/$$$ apiset3.js
call testjs app/$$$ udjson.js
call testjs app/$$$ udutilities.js
call testjs app/$$$ udmodule.js
call testjs modules/calculator udecalc_css.js
call testjs modules/editors udelist.js
call testjs modules/editors udetable.js
call testjs modules/editors udetext.js
call testjs modules/editors udedraw.js
call testjs modules/editors udehtml.js
call testjs modules/connectors udeconnector.js
call testjs modules/connectors udcsiteextract.js
call testjs modules/players udevideo.js
call testjs modules/tools clipboarder.js
call testjs modules/tools inserter.js
call testjs modules/tools rollbacker.js
call testjs modules/tools styler4editor.js
call testjs modules/udchart udechart.js
call testjs modules/$$$ udehooks.js

